name: Release
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        SERVER_VERSION: "3.5.1.${{github.run_number}}"

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 9

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Docker Image
        run: |
            sed -i "s|<Version>.*</Version>|<Version>${SERVER_VERSION}</Version>|" "DustyPig.Server/DustyPig.Server.csproj"
            docker buildx create --name mybuilder --driver=docker-container --use
            docker buildx build --platform linux/amd64,linux/arm64 . -f DustyPig.Server/Dockerfile --push --tag ghcr.io/dustypigtv/dustypig.server:v${SERVER_VERSION} --tag ghcr.io/dustypigtv/dustypig.server:latest
