name: Release
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 9

      # - name: Build Server
      #   run: |
      #       sed -i "s/\(<Version>\([0-9]\+\.\)\{3\}\)\([0-9]\+\)/\1${{github.run_number}}/" "DustyPig.Server/DustyPig.Server.csproj"
      #       dotnet publish "DustyPig.Server/DustyPig.Server.csproj" -c release -p:PublishProfile=FolderProfile -o publish
      #       rm -rf "publish/wwwroot/.well-known"
      #       cp -r "DustyPig.Server/wwwroot/.well-known" "publish/wwwroot"
      #       cd publish
      #       zip -rm9 ../DustyPig.Server.zip .
      #       cd ..

      # - uses: marvinpinto/action-automatic-releases@latest
      #   with:
      #       repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #       prerelease: false
      #       files: DustyPig.Server.zip
      #       automatic_release_tag: v3.4.0.${{github.run_number}}

      - name: 'Login to ghcr'
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
            docker build . --tag ghcr.io/dustypigtv/dustypig.server:latest
            docker push ghcr.io/dustypigtv/dustypig.server:latest    
              